### ISSUE TITLE
[2nd REVIEW-JOSS] - Comments on the manuscript

### ISSUE THREAD

**Issue by mirca** [daya6489/DriveML#10]
- I strongly suggest the removal of the sentence: "_These two features would be incorporated in the next release, and we are currently working on it._". The rationale being that the support for these features might not be as straightforward as the authors claim.

- Instances of "codes" should be written "code" instead.

- There are many wrong usages of the symbol "-" throughout the text.

- There are still several grammar and punctuation flaws in the text. See this: "_it performs various operations such as missing at random features, Date variable transformation, bulk interactions for numerical features, one-hot encoding for categorical variables and finally, feature selection using zero variance, correlation and Area under the curve (AUC) method._"

- I think the citation style is not very adequate specially for entries with many authors. Some lines in the text almost just includes a citation reference. In this case, you should use something like (FIRST_AUTHOR_LAST_NAME et. al. YEAR).

In general, the quality of the manuscript has improved, but I feel that it is yet not ready for publication due to various grammar inconsistencies. Please take a thorough look at this.

**Comment by sayanddude** [comment]
Hi @mirca ,
Please find below my response to each of the comments (my responses are  in italics):

- I strongly suggest the removal of the sentence: "These two features would be incorporated in the next release, and we are currently working on it.". The rationale being that the support for these features might not be as straightforward as the authors claim. -- _Thanks for your comment! The concerned sentence is removed from the latest version of the manuscript._

- Instances of "codes" should be written "code" instead.-- _We have corrected it!_

- There are many wrong usages of the symbol "-" throughout the text.- _Thanks for pointing this out! We have replace '-' with ':' wherever appropriate._

- There are still several grammar and punctuation flaws in the text. See this: "it performs various operations such as missing at random features, Date variable transformation, bulk interactions for numerical features, one-hot encoding for categorical variables and finally, feature selection using zero variance, correlation and Area under the curve (AUC) method."--- _Thanks for your comment! We have corrected the issue with the concerned line and have also done a thorough proof-reading to rectify some grammatical inconsistencies._

- I think the citation style is not very adequate specially for entries with many authors. Some lines in the text almost just includes a citation reference. In this case, you should use something like (FIRST_AUTHOR_LAST_NAME et. al. YEAR).-- _Thanks for pointing this out! We have corrected this issue in the latest version of the manuscript._

Overall, we have done another round of proof-reading (both manual and using tools such as, Grammarly) to remove any grammatical inconsistencies.
