### ISSUE TITLE
[REVIEW-JOSS] Vignette code does not work when using auto-prepped training set

### ISSUE THREAD

**Issue by ledell** [daya6489/DriveML#11]
I am getting errors running your vignette code with default settings.

The vignette currently goes the the process of creating an "auto-prepped" training set via the `autoDataprep()` function, but then neglects to use the auto-prepped dataset in the examples -- it uses the original `heart` data.frame.  Is that intentional?  It seems like your package is meant to first use `autoDataprep()` and then `autoMLmodel()` on the auto-prepped data.

If I try to use the auto-prepped version, I get errors.  It seems that there's some problem with how you're setting the range of mtry (it seems to not be actually based on the # of columns of the data, but possibly hard-coded?).

Here's the code to reproduce the error:

```
library(DriveML)

heart <- DriveML::heart

target <- "target_var"
prepdata <- autoDataprep(data = heart, target = target)
heart_prep_master <- prepdata$master_data
model_prep_master <- autoMLmodel(train = heart_prep_master, target = target)
```
Running `autoMLmodel()` on auto-prepped dataset gives this error (I've tried to run it a few times, same error).

```
Error: mtry can not be larger than number of variables in data. Ranger will EXIT now.
Error in ranger::ranger(formula = NULL, dependent.variable.name = tn,  : 
  User interrupt or internal error.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```
And the warnings all look like this:
```
> warnings()
Warning messages:
1: In randomForest.default(m, y, ...) : invalid mtry: reset to within valid range
```

Also, why is your vignette called "SmartML.html" when "SmartML" is the name of a different AutoML system that you evaluate in your paper?  I think it would make a lot more sense to call it "DriveML.html" or some other generic name to avoid any confusion.

**Comment by sayanddude** [comment]
Thank you for pointing this out! We have fixed the issue and corrected the vignette name.

**Comment by ledell** [comment]
Please merge changes into master and link to your fix here.

**Comment by daya6489** [comment]
@ledell Thank you for your comments. Here is the commit link https://github.com/daya6489/DriveML/commit/c2ea6573b4585e2b317fb99f7bdd44584ef3ac14

Please note that we have updated all the changes as suggested by you and some other updates in a single commit yesterday. 
The issue here was due to the "mtry" ranges provided by us for 'ranger' and 'randomforest' methods. We have fixed it in the utils.R file as shown in the screenshot below and can also be seen in the commit link shared above

![image](https://user-images.githubusercontent.com/17849762/97957035-21a81a00-1dd0-11eb-946d-227f1a0aed98.png)

**Comment by daya6489** [comment]
@ledell  we have also corrected the vignette name in the paper. Here is the commit link https://github.com/daya6489/DriveML/commit/f4088bc0630d196b0e026432eaf2ce7ca976db23 for the updated paper

**Comment by ledell** [comment]
This is now resolved.
