### ISSUE TITLE
[REVIEW-JOSS] PDP vignette on github.io package website is incomplete

### ISSUE THREAD

**Issue by ledell** [daya6489/DriveML#12]
This PDP vignette on the website is incomplete, so it should either be removed or completed: https://daya6489.github.io/DriveML/articles/auto_pdp.html

**Comment by sayanddude** [comment]
Thank you for the comment! For now we have removed the PDP vignette.

P.S.- Currently, it is in the "development" phase and not in the "master".

**Comment by ledell** [comment]
If I visit the link above, the partially finished vignette is still online.  This is not resolved.

Please link to commits, merged into master that show this as resolved.  In this case, the pkgdown site must also be updated to be considered resolved.

**Comment by daya6489** [comment]
@ledell Thank you for pointing this out. We have removed the incomplete vignette from the develop branch as well. Here is the commit link https://github.com/daya6489/DriveML/commit/d6096f674e1da330609ea3b6f2a678b8b09ed495

**Comment by ledell** [comment]
This is resolved.
