### ISSUE TITLE
[REVIEW-JOSS] Installation

### ISSUE THREAD

**Issue by mirca** [daya6489/DriveML#2]
The installation method reported is conditioned on the acceptance of the package into the Comprehensive R Archive Network (CRAN). Therefore, the package is not actually installable via the reported method. I suggest the authors to inform users how to install the package from its source code on GitHub either via ``R CMD INSTALL .``, where ``.`` is the root directory of the package, or via the devtools package: ``devtools::install_github(daya6489/DriveML)``.

**Comment by sayanddude** [comment]
Thanks for your comment! The DriveML package is now accepted in CRAN and it is available at https://cran.r-project.org/web/packages/DriveML/index.html. So, we have updated the “Installation” section in the Github repo with both ways to install the package i.e. via CRAN and devtools.
