### ISSUE TITLE
[REVIEW-JOSS] Affiliation

### ISSUE THREAD

**Issue by mirca** [daya6489/DriveML#3]
The affiliation of the authors are not clear. The acronyms "EDA", "AA", "DS", and "CoE" seem not to be defined anywhere in the manuscript.

**Comment by sayanddude** [comment]
Thanks for pointing this out! EDA AA & DS CoE stands for Enterprise Data Analytics- Advanced Analytics and Data Sciences Center of Excellence. We have updated the paper with the full form.
