### ISSUE TITLE
[REVIEW-JOSS] Comments on the Summary section

### ISSUE THREAD

**Issue by mirca** [daya6489/DriveML#4]
"In recent years, [...] automated machine learning has become very popular.".

- AutoML is undoubtedly super popular nowadays, however we shouldn't assume the reader
is familiar with that, therefore adding a reference here would be appropriate.

"and more (including some tech startups)"

- I am not sure how this helps to further convince the reader on the importance of AutoML.

"DriveML helps in implementing some of the pillars [...] by running the function [...]"

- What does "running the function" mean? What "function" are you referring to? Can this be written in a different, perhaps clearer way?

**Comment by sayanddude** [comment]
Thanks for your comments! We have provided an appropriate reference i.e. (Tuggener et al., 2019) for AutoML as suggested. We have also worked on the other two comments and have rewritten the specific lines.
