### ISSUE TITLE
[REVIEW-JOSS] Comments on Illustration section

### ISSUE THREAD

**Issue by mirca** [daya6489/DriveML#6]
The illustration section does not show how the package DriveML is actually used in practice.
It just compares the performance of state-of-the-art algorithms that are already available in
their respective packages in CRAN.

I identify two issues when the authors state "We also applied the DriveML package on much larger datasets and we got very encouraging results taking into account both the prediction accuracy and the time taken.": 1) which datasets are you referring to? 2) the accuracy or the
computational complexity is not actually related to DriveML, since it just provides wrappers around existing state-of-the-art algorithms. Is that correct?

In general, the benefit of using DriveML is not clearly explained. The use of the features "identifying pattern of missing values" and "HTML report using rmarkdown",
listed in Figure 2, which are supposed to be features available only in DriveML, are
not actually discussed in details in the manuscript.

**Comment by sayanddude** [comment]
Thanks for your comments! We agree about your specific comments for the illustration section and so we have rewritten this section entirely. The focus is now not on comparison of methods but how to practically use the DriveML package. Here we focus on the functionalities of DriveML viz., exploratory overview of the data, automated data preparation, automated machine learning model building and generating report in HTML. We use a publicly available dataset and write the corresponding R codes as well.

Regarding your comments on the unique features of DriveML mentioned in Table 1- "identifying pattern of missing values" and "HTML report using rmarkdown", we have updated the “Key Functionality” section of the paper where we have explained how the “autoMAR” function works and have provided a sample HTML report/vignette generated by DriveML that is published in CRAN.
