### ISSUE TITLE
[2nd REVIEW-JOSS] - Community Guidelines

### ISSUE THREAD

**Issue by mirca** [daya6489/DriveML#9]
Hi @sayanddude,

as part of the on-going JOSS review, could you please update the README and/or related documentations
in order to address how third parties would go about: 1) contributing to the software 2) reporting issues or problems with the software, and 3) seeking support?

Thanks.

**Comment by sayanddude** [comment]
Hi @mirca,
Thanks for your comments! We have now added two new files viz., CONTRIBUTING.md and  GOVERNANCE.md to address the points you have raised.

Thanks and Regards,
Sayan
